In [1]:
#importing pandas module
import pandas as pd

In [2]:
#creating series, it can contain any type of values and index.

pd_series = pd.Series([1, 3.14, True, 'apple', [1,2,3]], index=['a', 'b', 'c', 1, [1,2]])

print(pd_series)

#print(pd_series['a'])
# this is give issue, coz list([1,2]) present in the index is unhasable as list in pandas are mutable., coz of it when pandas index for faster retrieval it throws error. 
#We will not get error when printing the entire series like we did in first print, coz python lazily build internal index mapping and this is not detected that time.
#What we can do now is, use tuple as key (1,2) as tuple are immutable hence hashable.

pd_series_tupple = pd.Series([1, 3.14, True, 'apple', [1,2,3]], index=['a', 'b', 'c', 1, (1,2)]) #this will work, coz here instead of index having list, we have tuple.
print(pd_series_tupple['a'])

a                 1
b              3.14
c              True
1             apple
[1, 2]    [1, 2, 3]
dtype: object
1

In [ ]:
# we can create dictionary and then pass it on to the Series.

data = {'a': 1, 'b': 3.14, 'c': True, 1: 'mango', (1,2): [1,2,3]}

dict_series = pd.Series(data)

print(dict_series)

print(dict_series[(1,2)])

a                 1
b              3.14
c              True
1             mango
(1, 2)    [1, 2, 3]
dtype: object
[1, 2, 3]

array([1, 3.14, True, 'mango', list([1, 2, 3])], dtype=object)

count     5
unique    4
top       1
freq      2
dtype: int64

In [20]:
# creating dataframe using dictionary

data = {
    'Name': ['Mayank', 'Pranitha', 'Lucky', 'Tanamy'],
    'Age': [28, 26, 28, 29],
    'City': ['Agra', 'Nizamabad', 'Etawa', 'Nagpur'],
    'Salary': [15000, 20000, 25000, 30000]
}

pd_df = pd.DataFrame(data)

print(pd_df)

       Name  Age       City  Salary
0    Mayank   28       Agra   15000
1  Pranitha   26  Nizamabad   20000
2     Lucky   28      Etawa   25000
3    Tanamy   29     Nagpur   30000

In [22]:
# Shape: It's used to define the matrix of the dataframe. Like number_of_cols * number_of_rows. Returns a tuple.
df_shape = pd_df.shape
print(df_shape)

# columns: It's used to get the columns from a dataframe. We can add .tolist() to this get the columns in list format. Returns a list.
df_column = pd_df.columns
print(df_column_list)

# dtypes: This is used to get the datatypes of the columns present in the dataframe. Returns the object
df_dtypes = pd_df.dtypes
print(df_dtypes)

# head(n): Head is used get the top 'n' number of dataframe.
df_head = pd_df.head(2)
print(df_head)

(4, 4)
['Name', 'Age', 'City', 'Salary']
Name        str
Age       int64
City        str
Salary    int64
dtype: object
       Name  Age       City  Salary
0    Mayank   28       Agra   15000
1  Pranitha   26  Nizamabad   20000

In [ ]:
#Attribute and Methods in Series
# 1. Index: It provides the index values of the series. Returns array of values.
s_index = dict_series.index
display(s_index)

# 2. Values: Provides the values of the series. Returns an array.
s_values = dict_series.values
display(s_values)

# 3. dtype: Returns the datatypes of the columns.
s_dtype = dict_series.dtype
display(s_dtype)

# 4. value_counts: Returns the count of values present in the series.
s_value_counts = dict_series.value_counts()
display(s_value_counts)

# 5. isnull(): THis returns if any values of the series contains null or not.
s_isnull = dict_series.isnull()
display(s_isnull)

# 6. fillna(): This is used to replace NaN/null values with the speicified values in the function.
s_fillna = dict_series.fillna(' ')
display(s_fillna)

# 7. dropna(): This is used to drop the values in the series which are null/NaN.
s_dropna = dict_series.dropna()
display(s_dropna)

# 8. sort_values(): This is used to sort the values of series. It takes a parameter ascending, by default it's true, we can assign False to it so it gives decending values.
# Remember: It should only be applied when series contains values of same type.
#s_sort_values_desc = dict_series.sort_values(ascending=False)
#s_sort_values_asc = dict_series.sort_values()

# 9. sort_index(): This method is used to sort the index of the series in asc or desc order. It also takes ascending param.
# Remember: It should only be applied when series index are of same type.
s_sort_index = dict_series.sort_index()
display(s_sort_index)
s_sort_index_desc = dict_series.sort_index(ascending=False)
display(s_sort_index_desc)

Index(['a', 'b', 'c', 1, (1, 2)], dtype='object')

array([1, 3.14, True, 'mango', list([1, 2, 3])], dtype=object)

dtype('O')

1            2
3.14         1
mango        1
[1, 2, 3]    1
Name: count, dtype: int64

a         False
b         False
c         False
1         False
(1, 2)    False
dtype: bool

a                 1
b              3.14
c              True
1             mango
(1, 2)    [1, 2, 3]
dtype: object

a                 1
b              3.14
c              True
1             mango
(1, 2)    [1, 2, 3]
dtype: object

TypeError: '<' not supported between instances of 'int' and 'str'

In [36]:
#Dataframe Attributes

# 1. shape: Provides a tuple as output indicating number of rows, columns.
df_shape = pd_df.shape
display(df_shape)

# 2. columns: It provides list of columns in dataframe.
df_column = pd_df.columns
display(df_column)

# 3. Index: Returns the index/label of the rows.
# Default output of this is a RnageIndex(starrting, stop, step). Indicating starting value, ending value and how increment of each value.
df_index = pd_df.index
display(df_index)

# 4. Info(): It used to provide information about the dataframe. Also indicated the memory usage.
df_info = pd_df.info()
display(df_info)

# 5. describe: It provides the statistical description of the dataframe columns. Only those columns which have numerical values only.
df_describe = pd_df.describe()
display(df_describe)

# 6. Sample(n): THis is used to return random values from the data frame. We have to specify value of n indicating number of rows we want.
df_sample = pd_df.sample(n = 2)
display(df_sample)

# 7. memory_usage(): It provides memory consumption per column in bytes. It provides the memory_usage b y reference pointer pointing to pandas obj.
#deep=True: This additional parameter if added provides the actual memory usage by Python objects, like Str, int, etcx.
df_memory = pd_df.memory_usage()
display(df_memory)
df_memory = pd_df.memory_usage(deep=True)
display(df_memory)

# 8. size: It is used to return a int output (no.of rows * no. of cols)
df_size = pd_df.size
display(df_size) 

# 9. ndim: It determines the number of dimension of dataframe.
# For dataframe it's 2 as df contains rows and columns. 
# For a series it's 1 as it contains only single column.
# For a 3D array, it will be 3.
df_ndim = pd_df.ndim
display(df_ndim)

(4, 4)

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

RangeIndex(start=0, stop=4, step=1)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

None

             Age        Salary
count   4.000000      4.000000
mean   27.750000  22500.000000
std     1.258306   6454.972244
min    26.000000  15000.000000
25%    27.500000  18750.000000
50%    28.000000  22500.000000
75%    28.250000  26250.000000
max    29.000000  30000.000000

     Name  Age   City  Salary
0  Mayank   28   Agra   15000
2   Lucky   28  Etawa   25000

Index     132
Name       32
Age        32
City       32
Salary     32
dtype: int64

Index     132
Name      221
Age        32
City      220
Salary     32
dtype: int64

16

2