In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
#Detecting and Handling NaN values

#isnull() : It checks against each column and row, and returns a df showing true if its null and false if its not.
df_nulls = df.isnull()
display(df_nulls)
display(df_nulls.sum())  # It will show the count of nulls/NaN per column.

#fillna(): It is used to replace null/NaN values in the df with the specified value.
df_fillna_full = df.fillna(0)
display(df_fillna_full)

df_fillna_column = df[['year']].fillna(0)  #it will only replace nulls/NaN with 0 for this specific column. Returns only the row where it's applied.
display(df_fillna_column)

#dropna: It will drop the rows which has null/NaN values.
df_dropna = df.dropna()
display(df_dropna)

df_dropna_col = df[['year']].dropna()  #this will return only that row on which dropna is applied.
display(df_dropna_col)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze
12,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,Silver
14,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,Bronze
15,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,Bronze
21,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,Bronze
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,Bronze
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,Bronze
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,Bronze
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,Bronze

          year
0       1912.0
1       1912.0
2       1920.0
3       1920.0
4       1920.0
...        ...
308403  2022.0
308404  2022.0
308405  2022.0
308406  2022.0
308407  2022.0

[305807 rows x 1 columns]

In [ ]:
#Removing Duplicates

#duplicated(): It returns each index mentioning True or False based on if it's a duplicated row or not.
df_dup = df.duplicated()
print(df_dup)

df_dup_sum = df_dup.sum()  #it returns the count of total duplicate rows in the dataframe.
print(df_dup_sum)

#drop_duplicates(): It drop duplicate rows from the dataframe and returns the updated dataframe.
df_drop_dup = df.drop_duplicates()
display(df_drop_dup)

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Length: 308408, dtype: bool
126

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN