In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
#Detecting and Handling NaN values

#isnull() : It checks against each column and row, and returns a df showing true if its null and false if its not. Alternate to it is using .isna() -> It's like alias to isnull().
df_nulls = df.isnull()
display(df_nulls)
display(df_nulls.sum())  # It will show the count of nulls/NaN per column.

#notnull(): It checks against each column and row, and returns a df showing true if its not null and false if its not.
df_notnull = df.notnull()
display("/notnull", df_notnull)

#fillna(): It is used to replace null/NaN values in the df with the specified value.
df_fillna_full = df.fillna(0)
display(df_fillna_full)

df_fillna_column = df[['year']].fillna(0)  #it will only replace nulls/NaN with 0 for this specific column. Returns only the row where it's applied.
display(df_fillna_column)

df_fillna_mulcol = df.fillna({'noc': 'unknown', 'team': 'No Team'}) #it's used to fill multiple columns null/NaN with values.
display(df_fillna_mulcol)

df_ffill = df[['noc']].ffill(limit=3) #ffill method: It's a forward fill method, in this it's previous not null value present in the row and fill next rows with those values. We can provide limit, which means apply to next n consecutive null values. So it will fill next n consecutive nulls with the not null value.
display(df_ffill)

df_bfill = df[['team']].bfill() #bfill: It's backfill method, here it takes next null values present in the rows and fill the previous null rows.
display(df_bfill)

#dropna: It will drop the rows which has null/NaN values.
df_dropna = df.dropna()
display(df_dropna)

df_dropna_col = df[['year']].dropna()  #this will return only that row on which dropna is applied.
display(df_dropna_col)

df_dropna_axis = df.dropna(axis=1) #here axis refer to either row or column drop. So axis=1 drop the column with null vlaues, axis=0 will drop the row with null values.
display(df_dropna_axis)

df_dropna_how = df.dropna(how='all') #here how is a conditional drop. So if how='all' then it will drop the column only if all values are null, if how='any' then it will drop the column if there are any null values.
display(df_dropna_how)

df_dropna_thres = df.dropna(thresh=3) #thresh, refers to threshold value of not null for the rows need to be kept. Here so in the mentioned example the row will be kept if it contains 3 or more non null values.
display(df_dropna_thres)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,False,False,False,False,False,False,False,True,False,False,True
1,False,False,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,False,True,False,False,True
3,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
308403,False,False,False,False,False,False,False,True,False,False,True
308404,False,False,False,False,False,False,False,True,False,False,True
308405,False,False,False,False,False,False,False,False,False,False,True
308406,False,False,False,False,False,False,False,True,True,False,True
308407,False,False,True,False,False,False,True,True,False,False,True

year            2601
type            2601
discipline         1
event              0
as                 0
athlete_id         0
noc                1
team          186694
place          25215
tied               0
medal         264269
dtype: int64

'/notnull'

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,True,True,True,True,True,True,True,False,True,True,False
1,True,True,True,True,True,True,True,True,False,True,False
2,True,True,True,True,True,True,True,False,True,True,False
3,True,True,True,True,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...
308403,True,True,True,True,True,True,True,False,True,True,False
308404,True,True,True,True,True,True,True,False,True,True,False
308405,True,True,True,True,True,True,True,True,True,True,False
308406,True,True,True,True,True,True,True,False,False,True,False
308407,True,True,False,True,True,True,False,False,True,True,False

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,0,17.0,True,0
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,0.0,False,0
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,0,32.0,True,0
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,0
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,0
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,0,26.0,False,0
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,0,28.0,False,0
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,0
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,0,0.0,False,0
308407,2022.0,Winter,0,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,0,0,24.0,False,0

          year
0       1912.0
1       1912.0
2       1920.0
3       1920.0
4       1920.0
...        ...
308403  2022.0
308404  2022.0
308405  2022.0
308406  2022.0
308407  2022.0

[308408 rows x 1 columns]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,No Team,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,No Team,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,No Team,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,No Team,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,No Team,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,unknown,No Team,24.0,False,NaN

        noc
0       FRA
1       FRA
2       FRA
3       FRA
4       FRA
...     ...
308403  SVK
308404  SWE
308405  SWE
308406  SWE
308407  SWE

[308408 rows x 1 columns]

                   team
0        Jean Montariol
1        Jean Montariol
2       Jeanne Vaussard
3       Jeanne Vaussard
4       Jacques Brugnon
...                 ...
308403           Sweden
308404           Sweden
308405           Sweden
308406              NaN
308407              NaN

[308408 rows x 1 columns]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze
12,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,Silver
14,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,Bronze
15,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,Bronze
21,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,Bronze
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,Bronze
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,Bronze
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,Bronze
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,Bronze

          year
0       1912.0
1       1912.0
2       1920.0
3       1920.0
4       1920.0
...        ...
308403  2022.0
308404  2022.0
308405  2022.0
308406  2022.0
308407  2022.0

[305807 rows x 1 columns]

In [ ]:
#Removing Duplicates

#duplicated(): It returns each index mentioning True or False based on if it's a duplicated row or not.
df_dup = df.duplicated()
print(df_dup)

df_dup_sum = df_dup.sum()  #it returns the count of total duplicate rows in the dataframe.
print(df_dup_sum)

df_subset = df.duplicated(subset=['noc']) #here subset is used to check the duplicates in that particular column.
display(df_subset)

df_keep = df.duplicated(keep='last') #here keep refes to which value to keep. By default the first occurence of the value is considered unique and rest other occurences as duplicates. Keep has two values, first and last. First means keep first value occurence as unique its default behaviour as well, and last which means keep last occurence as unique
display(df_keep)

#drop_duplicates(): It drop duplicate rows from the dataframe and returns the updated dataframe.
df_drop_dup = df.drop_duplicates()
display(df_drop_dup)

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Length: 308408, dtype: bool
126

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
#Type casting and renaming

#astype: It's used to convert the datatype of column.
df['Position'] = df['place'].astype('Int64') 
display(df)

#category: It's a special datatype in pandas. It's used for values which has categorical value like Male/Female, list of cities, countires, etc. This operation saves memory. Performing operations on this becomes faster and efficient.
df['medal'] = df['medal'].astype('category') # now the datatype of medal column will change from str to category.
display(df)

df['year'] = pd.to_numeric(df['year'], errors='coerce') #this is hard changing of column dtype, basically if values can change, they'll convert into numeric, those values which can't be converted into numeric will change to NaN as mentioned by errors attribute.
display(df)

#renaming
df_renamed = df.rename(columns = {'noc': 'name of country'}) #rename: can rename multiple columns at once. Format is columns={'old_name': 'new_name'}
display(df_renamed)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Position
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,17
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,<NA>
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,32
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,8
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,26
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,28
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,13
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,<NA>
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,24

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Position
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,17
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,<NA>
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,32
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,8
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,26
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,28
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,13
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,<NA>
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,24

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Position
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,17
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,<NA>
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,32
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,8
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,26
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,28
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,13
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,<NA>
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,24

,year,type,discipline,event,as,athlete_id,name of country,team,place,tied,medal,Position
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,17
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,<NA>
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,32
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,8
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,26
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,28
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,13
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,<NA>
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,24