In [1]:
import pandas as pd

In [7]:
#TimeSeries: In this section we will talk about how to perform Time series operation on Dataframe.
#date_range: It's a method in pandas library, which is used to create range of dates. Parameter: start date, end date, period:indicating how many dates to generate from starting_date, freq: determines it should be days, month, sec, mins.
#It returns DatetimeIndex
dates = pd.date_range('2026-05-01', periods=5, freq='D')
values = [100, 120, 110, 130, 125]

dates_y = pd.date_range('2026-05-01', periods=5, freq='YE')

df_ts = pd.DataFrame({'Date': dates_y, 'Value': values})
display(df_ts)

#Extracting days, years, month.

df_ts['days'] = df_ts['Date'].dt.day
df_ts['day_name'] = df_ts['Date'].dt.day_name()
df_ts['month'] = df_ts['Date'].dt.month
df_ts['year'] = df_ts['Date'].dt.year

display(df_ts)

#formatting date: We can format the date format by passing format attribute to the data.
df_date = pd.to_datetime('2026-05-18', format="%d/%m/%Y")
display(df_date)

        Date  Value
0 2026-12-31    100
1 2027-12-31    120
2 2028-12-31    110
3 2029-12-31    130
4 2030-12-31    125

        Date  Value  days  day_name  month  year
0 2026-12-31    100    31  Thursday     12  2026
1 2027-12-31    120    31    Friday     12  2027
2 2028-12-31    110    31    Sunday     12  2028
3 2029-12-31    130    31    Monday     12  2029
4 2030-12-31    125    31   Tuesday     12  2030

ValueError: time data "2026-05-18" doesn't match format "%d/%m/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [8]:
#Rolling Windows: It means taking a fixed sized window(num of rows) and performing calculation over that moving window.
#Scenario: If we want to find the rolling average of sales, we can use it. We can specify window like we want rolling average from third day.
df_ts['rolling_mean'] = df_ts['Value'].rolling(window=3).mean()
display(df_ts)

        Date  Value  days  day_name  month  year  rolling_mean
0 2026-12-31    100    31  Thursday     12  2026           NaN
1 2027-12-31    120    31    Friday     12  2027           NaN
2 2028-12-31    110    31    Sunday     12  2028    110.000000
3 2029-12-31    130    31    Monday     12  2029    120.000000
4 2030-12-31    125    31   Tuesday     12  2030    121.666667