In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
#groupby: This is used to get the dataframe grouped by a certain column. It will be having aggregated values as well.

#single groupby column. 
# dropna: This parameter is used to include or exclude NaN/Nulls based on value provided to the parameter.
#reset_index: when we using aggregation function along with groupby, the aggregate function will not be having any label, so to provide that we use it along with the name of the column.
df_single_group = df.groupby('medal', dropna=False).size().reset_index(name='No_of_Medals')
display(df_single_group)

#multiple columns in groupby
df_mul_grpby = df.groupby(['noc', 'discipline'], dropna=False)['athlete_id'].nunique().reset_index(name='Num_of_Athelete')
display(df_mul_grpby)

#multiple columns in groupby along with multiple aggregations.
#agg(): We use it to perform the aggregation on the columns we want to add.
#There is two variation of agg function that we can use:
#1. When only uising single column for aggregation then, agg({'aggregate_col_name' = ('col_name', 'aggregation)})
#2. When using multiple columns in aggregation then, agg('aggregate_col_name' = ('col_name', 'aggregation'))
df_mul_agg = df.groupby(['noc', 'discipline', 'medal']).agg(
    Num_of_Athletes =('athlete_id', 'nunique'),
    Num_of_Medals =('medal', 'nunique')
)
display(df_mul_agg)

#transforms: It is used when we want to do groupby, but doesn't want to reduce the numbe rof rows. Like keeping the same df and adding a new column with the aggregation performed.
df['Avg_Country'] = df.groupby('discipline')['athlete_id'].transform('mean')
display(df)

#Normalization: It basically means scaling data to common range or value where the values become comparable.
df['Normalized'] = df.groupby('noc')['place'].transform(lambda x: x/x.mean())
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Avg_Country,Normalized
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,52819.298446,1.166091
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,52819.298446,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,52819.298446,2.194994
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,52819.298446,0.548749
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,52819.298446,0.274374
...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,105688.109589,1.205184
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,101727.009188,2.254786
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,101727.009188,1.046865
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,101727.009188,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,NaN,NaN