In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [5]:
#Adding columns

#map: It's used to transform the data. Map is applied to series or single column values.
df['has medal'] = df['medal'].notna().map({True: 'yes', False: 'no'}) #adding a new column based on other column value.
display(df)

#it can be applied to dictionary.
standing = {
    1: '1st place',
    2: '2nd place',
    3: '3rd place'
}

df['Standing'] = df['place'].map(standing)
display(df)

#apply: This is also used to transform data, but it can be applied to series, dataframe rows and columns.
df['is_medal'] = df['medal'].apply(lambda x: 1 if x == True else 0)
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,no,0
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,no,0
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,no,0
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,no,0
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,no,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,no,0
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,no,0
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,no,0
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,no,0
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,no,0

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal,Standing
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,no,0,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,no,0,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,no,0,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,no,0,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,no,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,no,0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,no,0,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,no,0,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,no,0,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,no,0,NaN

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal,Standing
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,no,0,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,no,0,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,no,0,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,no,0,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,no,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,no,0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,no,0,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,no,0,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,no,0,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,no,0,NaN

In [ ]:
#Sorting and Ranking

#sort_values: This function is used to sort the data, based on the column provides, multiple columns can also be provides in a list. We can change order based on ascending or decending keeping ascending flag true or false. Default is ascending true.
df_sorted = df.sort_values('year', ascending=False)
display(df_sorted)

df_sorted_multiple = df.sort_values(['year', 'type'], ascending=[True, False])
display(df_sorted_multiple)

#rank: It's to provide ranking to the data using specific column.
#parameters: 
# 1. ascending: Used to rank lowest to highest or highest to lowest. Default is lowest to highest.
# 2. method: This determines what will happen if two values are same. There are in total 5 methods:
#   i. average: It's default. So if there's a tie, it will take the average of the tie ranks and provide that value as rank value.
#   ii. min: It will provide both the values minimum rank. Like if for rank =3 there are three same values, it will assign 3 to all. Then it will skip the next n ranks (here n is number of tie values) and then provide next rank after the gap.
#   iii. max: It will provide both the values maximum rank. Like if for rank =3 there are three same values, it will assign 5 to all. Then it will skip the next n ranks (here n is number of tie values) and then provide next rank after the gap.
#   iv. first: It will provide the first occurence of tie value as lower rank and then subsequent values, subsequent ranks. Here no rank are skipped.
#   v. dense: here it will provide same rank to same value occurences, but it will not skip ranks like min and max.
# 3. pct: It is used to provide the rank in percentage. Range 0.1 - 1.0.
df_rank = df['place'].rank()
display(df_rank)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal,Standing
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,no,0,NaN
274176,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Ronalds Ķēniņš,128130,LAT,Latvia,11.0,False,NaN,no,0,NaN
274171,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Kristers Gudļevskis,128127,LAT,Latvia,NaN,False,NaN,no,0,NaN
274168,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Ralfs Freibergs,128125,LAT,Latvia,11.0,False,NaN,no,0,NaN
274149,2022.0,Winter,Bobsleigh (Bobsleigh),"Four, Open (Olympic)",Oskars Ķibermanis,128118,LAT,Latvia 1,5.0,False,NaN,no,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203177,NaN,NaN,Fencing,"Sabre, Individual, Men (Olympic)",Lóránt Mészáros,95189,HUN,NaN,5.0,False,NaN,no,0,NaN
203178,NaN,NaN,Fencing,"Sabre, Team, Men (Olympic)",Lóránt Mészáros,95189,HUN,Hungary,4.0,False,NaN,no,0,NaN
217586,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Georgios Pantos,100811,GRE,Athens,NaN,False,NaN,no,0,NaN
217587,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Alexandros Kalafatis,100812,GRE,Athens,NaN,False,NaN,no,0,NaN
271490,NaN,NaN,Diving (Aquatics),"Platform, Men (Intercalated)",Wilhelm Lindgren,127259,SWE,NaN,13.0,False,NaN,no,0,NaN

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal,Standing
50,1896.0,Summer,Tennis,"Singles, Men (Olympic)",J. Defert,13,FRA,NaN,8.0,True,NaN,no,0,NaN
51,1896.0,Summer,Tennis,"Doubles, Men (Olympic)",J. Defert,13,FRA,André Vacherot,NaN,False,NaN,no,0,NaN
244,1896.0,Summer,Tennis,"Singles, Men (Olympic)",John Pius Boland,79,GBR,NaN,1.0,False,Gold,yes,0,1st place
245,1896.0,Summer,Tennis,"Doubles, Men (Olympic)",John Pius Boland,79,GBR,Fritz Traun,1.0,False,Gold,yes,0,1st place
506,1896.0,Summer,Athletics,"100 metres, Men (Olympic)",Fritz Traun,162,GER,NaN,3.0,False,NaN,no,0,3rd place
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203177,NaN,NaN,Fencing,"Sabre, Individual, Men (Olympic)",Lóránt Mészáros,95189,HUN,NaN,5.0,False,NaN,no,0,NaN
203178,NaN,NaN,Fencing,"Sabre, Team, Men (Olympic)",Lóránt Mészáros,95189,HUN,Hungary,4.0,False,NaN,no,0,NaN
217586,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Georgios Pantos,100811,GRE,Athens,NaN,False,NaN,no,0,NaN
217587,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Alexandros Kalafatis,100812,GRE,Athens,NaN,False,NaN,no,0,NaN
271490,NaN,NaN,Diving (Aquatics),"Platform, Men (Intercalated)",Wilhelm Lindgren,127259,SWE,NaN,13.0,False,NaN,no,0,NaN

0         200496.5
1              NaN
2         242826.5
3         129009.0
4          61827.5
            ...
308403    230623.0
308404    235068.5
308405    178242.5
308406         NaN
308407    225478.0
Name: place, Length: 308408, dtype: float64

In [17]:
#filter: It's used to flter dataframe based on the label names. Column and row label names. Not filtering the df based on conditions applied to values in df.
#For example: We will filter the df based on lebles for columns and rows. By default it applies filter on column labels, but by changing axis = 0, we can make it apply on rows.
df_filtered = df.filter(items=['year', 'type'])
display(df_filtered)

df_filtered_rows = df.filter(items=[0,3,6,8], axis=0)
display(df_filtered_rows)

#like: It will filter the df with the columns, that meets the condition.
df_filter_like = df.filter(like='dis')
display(df_filter_like)

df_filter_grpby = df.groupby('noc').filter(lambda x: x['place'] <3)
display(df_filter_grpby)

          year    type
0       1912.0  Summer
1       1912.0  Summer
2       1920.0  Summer
3       1920.0  Summer
4       1920.0  Summer
...        ...     ...
308403  2022.0  Winter
308404  2022.0  Winter
308405  2022.0  Winter
308406  2022.0  Winter
308407  2022.0  Winter

[308408 rows x 2 columns]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,has medal,is_medal,Standing
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,no,0,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,no,0,NaN
6,1996.0,Summer,Tennis,"Doubles, Men (Olympic)",Arnaud Boetsch,2,FRA,Guillaume Raoux,17.0,True,NaN,no,0,NaN
8,1924.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean Borotra,3,FRA,Marguerite Billout,15.0,True,NaN,no,0,NaN

                    discipline
0                       Tennis
1                       Tennis
2                       Tennis
3                       Tennis
4                       Tennis
...                        ...
308403                    Luge
308404  Alpine Skiing (Skiing)
308405  Alpine Skiing (Skiing)
308406  Alpine Skiing (Skiing)
308407                     NaN

[308408 rows x 1 columns]

TypeError: filter function returned a Series, but expected a scalar bool