In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/results.csv')
display(df)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
#String methods: They are vectorized methods, which are NaN safe.

df_upper = df['as'].str.upper()
display(df_upper)

df_lower = df_upper.str.lower()
display(df_lower)

df_title = df_lower.str.title()
display(df_title)

df_strip = df_title.str.strip()
display(df_strip)

df_contains = df_title.str.contains("ean") #returns true for matching values, false which don't match.
display(df_contains)

df_split = df_title.str.split(" ", expand=True) #split the string based on delimeter provided in start, expand true means create a new column for each split value.
display(df_split)

0         JEAN-FRANÇOIS BLANCHY
1         JEAN-FRANÇOIS BLANCHY
2         JEAN-FRANÇOIS BLANCHY
3         JEAN-FRANÇOIS BLANCHY
4         JEAN-FRANÇOIS BLANCHY
                  ...
308403            MARIÁN SKUPEK
308404            ELSA FERMBÄCK
308405            HILMA LÖVBLOM
308406            HILMA LÖVBLOM
308407     CHARLOTTA SÄFVENBERG
Name: as, Length: 308408, dtype: str

0         jean-françois blanchy
1         jean-françois blanchy
2         jean-françois blanchy
3         jean-françois blanchy
4         jean-françois blanchy
                  ...
308403            marián skupek
308404            elsa fermbäck
308405            hilma lövblom
308406            hilma lövblom
308407     charlotta säfvenberg
Name: as, Length: 308408, dtype: str

0         Jean-François Blanchy
1         Jean-François Blanchy
2         Jean-François Blanchy
3         Jean-François Blanchy
4         Jean-François Blanchy
                  ...
308403            Marián Skupek
308404            Elsa Fermbäck
308405            Hilma Lövblom
308406            Hilma Lövblom
308407     Charlotta Säfvenberg
Name: as, Length: 308408, dtype: str

0         Jean-François Blanchy
1         Jean-François Blanchy
2         Jean-François Blanchy
3         Jean-François Blanchy
4         Jean-François Blanchy
                  ...
308403            Marián Skupek
308404            Elsa Fermbäck
308405            Hilma Lövblom
308406            Hilma Lövblom
308407     Charlotta Säfvenberg
Name: as, Length: 308408, dtype: str

0          True
1          True
2          True
3          True
4          True
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool

                    0           1    2    3    4    5    6    7
0       Jean-François     Blanchy  NaN  NaN  NaN  NaN  NaN  NaN
1       Jean-François     Blanchy  NaN  NaN  NaN  NaN  NaN  NaN
2       Jean-François     Blanchy  NaN  NaN  NaN  NaN  NaN  NaN
3       Jean-François     Blanchy  NaN  NaN  NaN  NaN  NaN  NaN
4       Jean-François     Blanchy  NaN  NaN  NaN  NaN  NaN  NaN
...               ...         ...  ...  ...  ...  ...  ...  ...
308403         Marián      Skupek  NaN  NaN  NaN  NaN  NaN  NaN
308404           Elsa    Fermbäck  NaN  NaN  NaN  NaN  NaN  NaN
308405          Hilma     Lövblom  NaN  NaN  NaN  NaN  NaN  NaN
308406          Hilma     Lövblom  NaN  NaN  NaN  NaN  NaN  NaN
308407      Charlotta  Säfvenberg  NaN  NaN  NaN  NaN  NaN  NaN

[308408 rows x 8 columns]