In [14]:
import pandas as pd
import numpy as np

In [ ]:
#Ques 6: Calculate total sales (quantity × price) by category and find the top 3 products by total sales
df['sales'] = df['quantity'] * df['price']
df_groupby = df.groupby('products')['sales'].sum().sort_values(ascending = False).head(3)
df_largest3 = df.groupby('products')['sales'].sum().nlargest(3)

In [10]:
#Ques 7: Create orders and customers DataFrames, merge them, and find total spending per customer.

orders = pd.DataFrame({ "order_id": [101,102,103,104,105], "customer_id": [1,2,1,3,2], "amount": [250,400,150,300,500] }) 
customers = pd.DataFrame({ "customer_id": [1,2,3], "name": ["Alice","Bob","Charlie"], "city": ["NYC","LA","Chicago"] })

df_merged = orders.merge(customers, how='left', on='customer_id')
df_output = df_merged.groupby('customer_id')['amount'].sum().reset_index(name='total_spend')
display(df_output)

   customer_id  total_spend
0            1          400
1            2          900
2            3          300

In [ ]:
#Ques 8: Create a pivot table of total sales by product (rows) and month (columns), including totals.

dates = pd.date_range("2024-01-01", periods=60, freq="D") 
products = np.random.choice(["A","B","C"], 60) 
sales = np.random.randint(100, 500, 60) 
df_s = pd.DataFrame({"date":dates,"product":products,"sales":sales})

df_s['month'] = df_s['date'].dt.to_period('M')

df_pivot = pd.pivot_table(df_s,
                          values='sales',
                          index='product',
                          columns='month',
                          aggfunc=sum,
                          margins=True
                          )

display(df_pivot)

month    2024-01  2024-02    All
product
A           2259     4517   6776
B           3213     2054   5267
C           3862     2729   6591
All         9334     9300  18634

In [35]:
#Ques 9: Extract the email domain, count domain occurrences, and identify Gmail users.

df_e = pd.DataFrame({ "user_id": [1,2,3,4,5,6], "email": ["alice@gmail.com","bob@yahoo.com","charlie@gmail.com", "diana@outlook.com","eve@gmail.com","frank@yahoo.com"] })
df_e['domain'] = df_e['email'].str.split('@').str[1]
df_output = df_e['domain'].str.contains('gmail.com')
display(df_output)
df_count = df_e[df_e['domain'] == 'gmail.com'].count()
display(df_count)

0     True
1    False
2     True
3    False
4     True
5    False
Name: domain, dtype: bool

user_id    3
email      3
domain     3
dtype: int64

In [45]:
#ques 10: Generate 90 days of daily sales. Compute a 7-day rolling average, find the best sales week, and get monthly totals.

dates = pd.date_range("2024-01-01", periods=90, freq="D") 
sales = np.random.randint(500, 2000, 90) 
df_ts = pd.DataFrame({"date":dates,"sales":sales})

df_ts['sales_avg'] = df_ts['sales'].rolling(window=7).mean()
display(df_ts)

df_best_sales = df_ts['sales_avg'].nlargest(1)
display(df_best_sales)

df_ts['month'] = df_ts['date'].dt.to_period('M')
display(df_ts)

df_ts_monthly = df_ts.groupby('month')['sales'].sum().reset_index(name='Total_Monthly_sales')
display(df_ts_monthly)

df_best_check = df_ts.loc[15]
display(df_best_check)

         date  sales    sales_avg
0  2024-01-01   1637          NaN
1  2024-01-02   1402          NaN
2  2024-01-03   1688          NaN
3  2024-01-04   1649          NaN
4  2024-01-05   1987          NaN
..        ...    ...          ...
85 2024-03-26   1244  1161.285714
86 2024-03-27   1936  1271.142857
87 2024-03-28   1866  1417.571429
88 2024-03-29   1823  1552.857143
89 2024-03-30   1601  1612.714286

[90 rows x 3 columns]

89    1612.714286
Name: sales_avg, dtype: float64

         date  sales    sales_avg    month
0  2024-01-01   1637          NaN  2024-01
1  2024-01-02   1402          NaN  2024-01
2  2024-01-03   1688          NaN  2024-01
3  2024-01-04   1649          NaN  2024-01
4  2024-01-05   1987          NaN  2024-01
..        ...    ...          ...      ...
85 2024-03-26   1244  1161.285714  2024-03
86 2024-03-27   1936  1271.142857  2024-03
87 2024-03-28   1866  1417.571429  2024-03
88 2024-03-29   1823  1552.857143  2024-03
89 2024-03-30   1601  1612.714286  2024-03

[90 rows x 4 columns]

     month  Total_Monthly_sales
0  2024-01                38744
1  2024-02                39321
2  2024-03                37169

date         2024-01-16 00:00:00
sales                        993
sales_avg                  977.0
month                    2024-01
Name: 15, dtype: object

In [43]:
dates = pd.date_range("2024-01-01", periods=90, freq="D") 
sales = np.random.randint(500, 2000, 90) 
df_ts = pd.DataFrame({"date":dates,"sales":sales}) 
df_ts.set_index("date", inplace=True) 
df_ts["rolling_7d"] = df_ts["sales"].rolling(7).mean() 
df_ts["week_total"] = df_ts["sales"].rolling(7).sum()
best_end = df_ts["week_total"].idxmax() 
print(best_end)
best_start = best_end - pd.Timedelta(days=6) 
print(f"Best week: {best_start.date()} to {best_end.date()}") 
print(df_ts.resample("ME")["sales"].sum())

2024-01-19 00:00:00
Best week: 2024-01-13 to 2024-01-19
date
2024-01-31    42479
2024-02-29    39591
2024-03-31    36765
Freq: ME, Name: sales, dtype: int64